### ISSUE TITLE
Enable/disable Ditto Cloud syncing after init

### ISSUE THREAD

**Issue by nihedr9** [getditto/DittoSwiftPackage#20]
is it possible to change the value of `enableDittoCloudSync` after ditto `init` and `startSync`?

For now, doing so will result in an app crash

**Comment by phatblat** [comment]
In order to change any values on your [`DittoIdentity`](https://software.ditto.live/cocoa/DittoSwift/4.4.5/api-reference/Enums/DittoIdentity.html) you need to create a new `Ditto` instance. Note that if you want to reuse the same working directory the old instance must be shut down and all references released first.

How are you updating that `enableDittoCloudSync` value in your app? What version of the Ditto SDK? Have you reported this crash to our Customer Experience team?

**Comment by phatblat** [comment]
Another approach that is more flexible (but more verbose) is to manually manage the websocket connection to Ditto Cloud. This allows for enabling and disabling the websocket connection using our `DittoTransportConfig` API. It's important to disable the `enableDittoCloudSync` so that the SDK doesn't automatically set up this websocket connection.

```swift
let appID = "7640041E-FA3B-4F44-ABD2-6ED1A560A7D8"
let playgroundToken = "********"
let dittoCloud = "wss://\(appID).cloud.ditto.live:443"
let identity = DittoIdentity.onlinePlayground(appID: appID, token: playgroundToken,
                                              enableDittoCloudSync: false)
let ditto = Ditto(identity: identity)
var onlineConfig = DittoTransportConfig()
onlineConfig.connect.webSocketURLs.insert(dittoCloud) // Connect to Ditto Cloud
ditto.transportConfig = onlineConfig
try! ditto.startSync()
```

At this point the app will be connected to the Ditto Cloud as if you had enabled `enableDittoCloudSync`. Later, you can disable the connection to Ditto Cloud by applying a different `DittoTransportConfig` like so:

```swift
var offlineConfig = DittoTransportConfig()
offlineConfig.connect.webSocketURLs.remove(dittoCloud) // Disconnect from Ditto Cloud
ditto.transportConfig = offlineConfig
```

Note that applying a `DittoTransportConfig` does not require restarting sync or creating a new `Ditto` instance.

**Comment by skylerjokiel** [comment]
@nihedr9, reviewing this relative to the docs issue opened about it. https://github.com/getditto/docs/issues/727

I'm a bit confused about the problem here and if this is a work around or a valid solution

It sound like it's a bug if ditto crashes when you update the enableDittoCloudSync value. 

@phatblat are you saying that if you have 2 transport configs that you can swap them in the middle of a ditto instance without impacting sync?
